spring.application.name=sistema_pedidos

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/artesanos}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:72000000}

cors.origins=${CORS_ORIGINS:http://localhost:5173,http://127.0.0.1:5173,http://192.168.0.60,*}

printer.default-port=${PRINTER_DEFAULT_PORT:9100}
printer.char-width=${PRINTER_CHAR_WIDTH:48}

impresora.cocina.ip=${IMPRESORA_COCINA_IP:192.168.1.200}
impresora.factura.ip=${IMPRESORA_FACTURA_IP:192.168.1.100}